version: '3.9'
services:
  frontend:
    build:
      context: ./frontend/NutriTrack
    ports:
      - "5173:80" # Map 5173 on the host to 80 in the container
    expose:
      - "80" # Make port 80 accessible to other services in the Docker network

  ngrok:
    image: ngrok/ngrok
    ports:
      - "4040:4040" # Expose the Ngrok web interface
    command: http frontend:80 # Use port 80 (the internal container port)
    environment:
      NGROK_AUTHTOKEN: "2p00Eb98vjGt3HwdtVcbs5BqlEp_65rewtqqomVuTv3MrVY7t"

  backend:
    build:
      context: ./backend/nutriTrack
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/nutritrack
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=yourpassword

  flask-server:
    build:
      context: ./flask
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: nutritrack
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db_data:
