# Use the official MySQL 8.0 image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=yourpassword
ENV MYSQL_DATABASE=nutritrack
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=userpassword

# Expose MySQL default port
EXPOSE 3306

# Start MySQL
CMD ["mysqld"]
